### ISSUE TITLE
0x432d2d : Hunter Price, Andrei Cozma, Jacob Isber, Dani Shekoury

### ISSUE THREAD

**Issue by hunterprice04** [utk-cs/README-Fall2020#13]
teamName : **0x432d2d**

> name : Hunter Price  
> netid : hprice7  
> git : hunterprice04

> name : Andrei Cozma 
> netid : acozma 
> git : andreicozma1

> name : Jacob Isber  
> netid : jisber
> git : jisber

> name : Dani Shekoury
> netid : dshekou1
> git : DaniShekoury

**Comment by hunterprice04** [comment]
Sorry about that. his handle is @DaniShekoury

**Comment by robobenklein** [comment]
Your team has been invited!
