### ISSUE TITLE
[Team] Void* : John Sadik, Knox Cavitt, Jackson Walker, Chase Hunter

### ISSUE THREAD

**Issue by John-Sadik** [utk-cs/README-Fall2020#15]
Team Name: Void* 

Name: John Sadik
NetID: jsadik
git: John-Sadik

Name: Knox Cavitt
NetID: kcavitt
git: kcavitt

Name: Jackson Walker
NetID: jwalk148
git: jwalk148

Name: Chase Hunter
NetID: thunte11
git: chunter-202

**Comment by robobenklein** [comment]
Your team has been made and members invited! Mention me for any other problems!
