### ISSUE TITLE
Ahmadre Darrisaw, Jack Hutchins, and Thomas Leonard 

### ISSUE THREAD

**Issue by ORANG3Koolade4** [utk-cs/README-Fall2020#22]
adarrisa
jhutch26
tleonar5

**Comment by robobenklein** [comment]
Remember to also give us their github account names!

**Comment by jball1997** [comment]
Also do you have a team name?

**Comment by ORANG3Koolade4** [comment]
Team Name: Segmentation Violation 
Github Account Names: Thomas54321, jack121999, and ORANG3Koolade4

**Comment by robobenklein** [comment]
Your team has been created and you've been invited!
