### ISSUE TITLE
Zachery Creech and Nicholas Creech

### ISSUE THREAD

**Issue by zach7creech** [utk-cs/README-Fall2020#23]

**Comment by zach7creech** [comment]
Looking for teammate(s), don't know how to add labels.
github: zach7creech ncreech1
NetID: zcreech ncreech1

**Comment by noah-22** [comment]
I'll be working with Dylan Lomax. Want to join our team?

| Name             | netid  | Git handle |
|------------------|--------|------------|
| Noah Burgin (me) | noah22 | noah-22    |
| Dylan Lomax      | dlomax | Maze-Mind  |

**Comment by zach7creech** [comment]
That sounds good, thanks guys.

**Comment by robobenklein** [comment]
Awesome, want to choose a team name?

**Comment by noah-22** [comment]
Join this [GroupMe](https://groupme.com/join_group/61815348/JG9hJa5a) and we'll discuss @zach7creech

**Comment by noah-22** [comment]
We'll go by "Smells Like Team Spirit" @robobenklein @AZHenley

**Comment by robobenklein** [comment]
Team created and invited!
