### ISSUE TITLE
Terryl Dodson, James Simmons, Ryan Stewart

### ISSUE THREAD

**Issue by terryldodson** [utk-cs/README-Fall2020#25]
All 3 would like to be in the same group:

netid @ username
jsimmo58 @simmonsj330
tdodson3 @terryldodson
rstewa35 @rstewa35

**Comment by robobenklein** [comment]
got a team name in mind?

**Comment by terryldodson** [comment]
You can just make one for us

**Comment by robobenklein** [comment]
Created and invited!
