### ISSUE TITLE
Jan Jakowski, Justin Adamson, Tan Nguyen <team>

### ISSUE THREAD

**Issue by jjakow** [utk-cs/README-Fall2020#26]
We are team for CS 340
Teamname: JJT (currently)

netid's:
Jan Jakowski (netid: jjakows1, github: jjakow)
Justin Adamson (netid: jadamso2, github: Just1nA)
Tan Nguyen (netid: tnguye85, github: tnguye85)

**Comment by robobenklein** [comment]
Created and invited!
