### ISSUE TITLE
Tyler Beichler, Austin Marianski, Trent Florey, and Parker Sherrill group

### ISSUE THREAD

**Issue by tdbucks** [utk-cs/README-Fall2020#30]
Team Name: TBD

**Comment by tdbucks** [comment]
Tyler - @tdbucks - tbeichle
Trent - @tflorey - tflorey
Austin - @Amaryans - amaryans
Parker - @psherrill24 - psherri1

**Comment by robobenklein** [comment]
Are you saying the team name is literally "TBD" or you haven't decided yet? XD

**Comment by tdbucks** [comment]
We hadn't decided yet. Let's just do "team-DCIsBetter"
