### ISSUE TITLE
"Main() Event": Sebastian Mobo, Clark Hathaway, Josh Mandzak

### ISSUE THREAD

**Issue by stmobo** [utk-cs/README-Fall2020#4]
Sebastian Mobo (@stmobo), Clark Hathaway (@chathawa), and Josh Mandzak (@jmandzak) have formed a team of three known as the "Main() Event".

**Comment by robobenklein** [comment]
@stmobo @chathawa @jmandzak can I get your netIDs?

**Comment by stmobo** [comment]
My netID is `smobo`.

**Comment by robobenklein** [comment]
You've all been invited to the org! Good to go
